import { csvCell, csvDocument } from "@/lib/csv";
import type { ClientPaymentEntry } from "@/lib/clients";

type StatementPayment = Pick<
  ClientPaymentEntry,
  "paidAt" | "createdAt" | "invoiceNumber" | "description" | "amountDisplay" | "status" | "paymentMethod" | "receiptNumber"
>;

const HEADERS = ["Date", "Invoice", "Description", "Amount", "Status", "Payment method", "Receipt"];

/**
 * The client's payment statement as CSV. Dates and amounts are generated by the
 * app, so they stay exactly as shown (a refund's leading minus must survive);
 * everything a person typed goes through csvCell's formula guard (lib/csv.ts).
 */
export function buildPaymentStatementCsv(payments: StatementPayment[]): string {
  return csvDocument([
    HEADERS.map((title) => csvCell(title)),
    ...payments.map((payment) => [
      csvCell(payment.paidAt || payment.createdAt, { literal: true }),
      csvCell(payment.invoiceNumber),
      csvCell(payment.description || "Manual ledger entry"),
      csvCell(payment.amountDisplay, { literal: true }),
      csvCell(payment.status),
      csvCell(payment.paymentMethod || "Manual"),
      csvCell(payment.receiptNumber),
    ]),
  ]);
}
